"""Generate the per-vulnbox bootstrap script served by /admin/bootstrap.

The analysis box's wizard (`iris-setup --init-analysis`) drops:

  - an ed25519 keypair under IRIS_BOOTSTRAP_KEY_PATH (private)
  - the corresponding public key in the rsync-target's authorized_keys

so that any new vulnbox can `curl <analysis>:5000/api/admin/bootstrap | sudo bash`
to enroll itself, write its .env, and bring up `suricata-ips,vulnbox-agent`
with a shared local.rules pulled from the analysis box's Settings page.

The endpoint is gated by the same basic-auth as the other /admin/* routes.
"""

from __future__ import annotations

import os
from pathlib import Path
from string import Template

KEY_PATH = Path(os.environ.get(
    "IRIS_BOOTSTRAP_KEY_PATH", "/run/iris-keys/id_ed25519"
))


_BOOTSTRAP_TEMPLATE = Template(r"""#!/usr/bin/env bash
# iris vulnbox bootstrap - generated per-request by /admin/bootstrap.
# Run on a fresh VM as root:
#   curl -fsSL -u user:pass http://<analysis-host>:5000/admin/bootstrap | sudo bash
#
# Pull-mode design: the vulnbox just runs Suricata-IPS. The analysis box
# (whose public key is embedded below) ssh's in to fetch eve.json and
# pcaps. The vulnbox does not push anything outbound, which means it
# works in one-way gamenets where vulnbox -> player traffic is dropped.
set -euo pipefail

REPO="$${IRIS_REPO:-$IRIS_REPO_DEFAULT}"
DEST="$${IRIS_DEST:-/opt/iris}"
NFQUEUE_CHAINS_OVERRIDE="$${NFQUEUE_CHAINS:-FORWARD}"
NFQUEUE_IFACE_OVERRIDE="$${NFQUEUE_IFACE:-}"
HOSTNAME_TAG="$$(hostname | tr -c '[:alnum:]._-' '_')"

echo "[iris-bootstrap] cloning $$REPO -> $$DEST"
if [ ! -d "$$DEST/.git" ]; then
  git clone "$$REPO" "$$DEST"
else
  git -C "$$DEST" fetch --depth 1 origin "$IRIS_REF" || true
  git -C "$$DEST" checkout "$IRIS_REF" || true
  git -C "$$DEST" reset --hard "origin/$IRIS_REF" || true
fi

# Authorize the analysis box's public key so its fetcher can pull
# /opt/iris/{traffic,suricata-runtime/log/eve.json} over SSH. Idempotent.
echo "[iris-bootstrap] authorizing analysis-box public key for /root SSH"
mkdir -p /root/.ssh
chmod 700 /root/.ssh
ANALYSIS_PUB="$SSH_PUBLIC_KEY"
touch /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys
if ! grep -qF "$$ANALYSIS_PUB" /root/.ssh/authorized_keys; then
  echo "$$ANALYSIS_PUB" >> /root/.ssh/authorized_keys
fi

echo "[iris-bootstrap] writing .env (hostname tag: $$HOSTNAME_TAG)"
cat > "$$DEST/.env" <<EOF
# Generated by iris /admin/bootstrap on $$(date -u +%FT%TZ).
# Pull-mode vulnbox: the analysis box fetches over SSH; nothing is
# pushed outbound from this host. Do not check this file in.
COMPOSE_PROFILES=suricata-ips

SURICATA_DIR_HOST=./suricata-runtime
TRAFFIC_DIR_HOST=./traffic
TRAFFIC_DIR_DOCKER=/traffic

# NFQUEUE / Suricata-IPS. NFQUEUE_IFACE / NFQUEUE_CHAINS may be overridden
# by setting them in the curl-bash environment, e.g.:
#   curl ... | NFQUEUE_IFACE=game NFQUEUE_CHAINS=FORWARD sudo -E bash
NFQUEUE_NUM=0
NFQUEUE_IFACE=$${NFQUEUE_IFACE_OVERRIDE}
NFQUEUE_CHAINS=$${NFQUEUE_CHAINS_OVERRIDE}
# 22 (ssh) is the lifeline; 53/123/1900/5353 are pure noise.
NFQUEUE_SKIP_PORTS=22,53,123,1900,5353
NFQUEUE_IPV6=0
SURICATA_UPDATE_ENABLE=0
EMIT_SID_TAGS=1

# Game-time placeholders (only relevant on the analysis box; harmless here):
TICK_START=2026-01-01T00:00:00Z
TICK_LENGTH=120000
FLAG_REGEX=[A-Z0-9]{31}=
TEAM_ID=0
VM_IP=0.0.0.0
EOF

mkdir -p "$$DEST/suricata-runtime/etc" "$$DEST/suricata-runtime/lib/rules" \
         "$$DEST/suricata-runtime/log" "$$DEST/traffic"

echo "[iris-bootstrap] starting docker compose"
cd "$$DEST"
docker compose --profile suricata-ips up -d --build

echo "[iris-bootstrap] done. tail logs with:"
echo "  sudo docker logs -f iris-suricata-ips-1"
echo "  sudo docker logs -f iris-iptables-init-1"
echo
echo "[iris-bootstrap] register this host with the analysis box's fetcher:"
echo "  add  $${HOSTNAME_TAG}=<this-host-ip>  to VULNBOX_LIST in the analysis"
echo "  box's .env, then  docker compose up -d --no-deps fetcher"
""")


def render_bootstrap() -> tuple[str, int]:
    """Return (body, http_status).

    The status is 503 when prerequisites (the key file) aren't in place,
    so an operator can curl the endpoint and immediately see what's wrong.
    """
    pub_path = KEY_PATH.with_suffix(KEY_PATH.suffix + ".pub") if KEY_PATH.suffix \
        else Path(str(KEY_PATH) + ".pub")
    if not pub_path.exists():
        return (
            "# bootstrap unavailable\n"
            f"# {pub_path} not present on the analysis box.\n"
            "# Run iris-setup --init-analysis to generate the keypair.\n",
            503,
        )

    public_key = pub_path.read_text(encoding="utf-8").strip()

    body = _BOOTSTRAP_TEMPLATE.substitute(
        IRIS_REPO_DEFAULT=os.environ.get("IRIS_REPO_URL", "https://github.com/caverav/iris.git"),
        IRIS_REF=os.environ.get("IRIS_REPO_REF", "master"),
        SSH_PUBLIC_KEY=public_key,
    )
    return (body, 200)
