"""Generate the per-vulnbox bootstrap script served by /admin/bootstrap.

The analysis box's wizard (`iris-setup --init-analysis`) drops:

  - an ed25519 keypair under IRIS_BOOTSTRAP_KEY_PATH (private)
  - the corresponding public key in the rsync-target's authorized_keys

so that any new vulnbox can `curl <analysis>:5000/api/admin/bootstrap | sudo bash`
to enroll itself, write its .env, and bring up `suricata-ips,vulnbox-agent`
with a shared local.rules pulled from the analysis box's Settings page.

The endpoint is gated by the same basic-auth as the other /admin/* routes.
"""

from __future__ import annotations

import os
from pathlib import Path
from string import Template

KEY_PATH = Path(os.environ.get(
    "IRIS_BOOTSTRAP_KEY_PATH", "/run/iris-keys/id_ed25519"
))


_BOOTSTRAP_TEMPLATE = Template(r"""#!/usr/bin/env bash
# iris vulnbox bootstrap - generated per-request by /admin/bootstrap.
# Run on a fresh VM as root:
#   curl -fsSL -u user:pass http://<analysis-host>:5000/api/admin/bootstrap | sudo bash
set -euo pipefail

REPO="$${IRIS_REPO:-$IRIS_REPO_DEFAULT}"
DEST="$${IRIS_DEST:-/opt/iris}"
ANALYSIS_API="$ANALYSIS_API"
ADMIN_USER="$ADMIN_USER"
ADMIN_PASS_B64="$ADMIN_PASS_B64"
SSH_DEST="$SSH_DEST"
HOSTNAME_TAG="$$(hostname | tr -c '[:alnum:]._-' '_')"

echo "[iris-bootstrap] cloning $$REPO -> $$DEST"
if [ ! -d "$$DEST/.git" ]; then
  git clone "$$REPO" "$$DEST"
else
  git -C "$$DEST" fetch --depth 1 origin "$IRIS_REF" || true
  git -C "$$DEST" checkout "$IRIS_REF" || true
fi

echo "[iris-bootstrap] dropping SSH key"
mkdir -p "$$DEST/vulnbox-agent"
umask 077
cat > "$$DEST/vulnbox-agent/id_ed25519" <<'__IRIS_KEY_EOF__'
$SSH_PRIVATE_KEY
__IRIS_KEY_EOF__
chmod 600 "$$DEST/vulnbox-agent/id_ed25519"
umask 022

echo "[iris-bootstrap] writing .env (hostname tag: $$HOSTNAME_TAG)"
cat > "$$DEST/.env" <<EOF
# Generated by iris /admin/bootstrap on $$(date -u +%FT%TZ).
# Do not check this file in.
COMPOSE_PROFILES=suricata-ips,vulnbox-agent

SURICATA_DIR_HOST=./suricata-runtime
TRAFFIC_DIR_HOST=./traffic
TRAFFIC_DIR_DOCKER=/traffic

# Tagging: every upload from this VM is namespaced by hostname so a
# shared rsync target on the analysis box doesn't see collisions.
VULNBOX_HOSTNAME=$${HOSTNAME_TAG}

# Analysis-side settings
VULNBOX_SSH_DEST=$$SSH_DEST
SHIP_INTERVAL=30
IRIS_API_BASE=$$ANALYSIS_API
IRIS_ADMIN_USER=$$ADMIN_USER
IRIS_ADMIN_PASS=$$(printf '%s' "$$ADMIN_PASS_B64" | base64 -d)
PULL_INTERVAL=10

# NFQUEUE / Suricata-IPS
NFQUEUE_NUM=0
NFQUEUE_IFACE=
NFQUEUE_CHAINS=INPUT,OUTPUT,FORWARD,DOCKER-USER
NFQUEUE_IPV6=1
SURICATA_UPDATE_ENABLE=0
EMIT_SID_TAGS=1

# Game-time placeholders (only relevant on the analysis box; harmless here):
TICK_START=2026-01-01T00:00:00Z
TICK_LENGTH=120000
FLAG_REGEX=[A-Z0-9]{31}=
TEAM_ID=0
VM_IP=0.0.0.0
EOF

mkdir -p "$$DEST/traffic"

echo "[iris-bootstrap] starting docker compose"
cd "$$DEST"
docker compose --profile suricata-ips --profile vulnbox-agent up -d --build

echo "[iris-bootstrap] done. tail logs with:"
echo "  sudo docker logs -f iris_shipper_1"
echo "  sudo docker logs -f iris_suricata-ips_1"
""")


def render_bootstrap() -> tuple[str, int]:
    """Return (body, http_status).

    The status is 503 when prerequisites (the key file) aren't in place,
    so an operator can curl the endpoint and immediately see what's wrong.
    """
    if not KEY_PATH.exists():
        return (
            "# bootstrap unavailable\n"
            f"# {KEY_PATH} not present on the analysis box.\n"
            "# Run iris-setup --init-analysis to generate one.\n",
            503,
        )

    private_key = KEY_PATH.read_text(encoding="utf-8").rstrip() + "\n"
    api_base = os.environ.get("IRIS_BOOTSTRAP_API_BASE", "")
    ssh_dest = os.environ.get("VULNBOX_SSH_DEST", "")
    if not api_base or not ssh_dest:
        return (
            "# bootstrap not configured\n"
            "# Set IRIS_BOOTSTRAP_API_BASE and VULNBOX_SSH_DEST in the analysis box .env.\n",
            503,
        )

    # We pass the admin password to the bootstrap target via base64 so a
    # password containing $, `, or " survives heredoc expansion. The new
    # vulnbox decodes it back before writing it to its .env.
    import base64
    admin_pass = os.environ.get("IRIS_ADMIN_PASS", "")
    admin_pass_b64 = base64.b64encode(admin_pass.encode("utf-8")).decode("ascii")

    body = _BOOTSTRAP_TEMPLATE.substitute(
        IRIS_REPO_DEFAULT=os.environ.get("IRIS_REPO_URL", "https://github.com/caverav/iris.git"),
        IRIS_REF=os.environ.get("IRIS_REPO_REF", "master"),
        ANALYSIS_API=api_base,
        ADMIN_USER=os.environ.get("IRIS_ADMIN_USER", "admin"),
        ADMIN_PASS_B64=admin_pass_b64,
        SSH_DEST=ssh_dest,
        SSH_PRIVATE_KEY=private_key,
    )
    return (body, 200)
